modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Sniffity/SniffitysCreatures/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${mod_id}.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    versionRange="${geckolib_version_range}"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="smartbrainlib"
    mandatory=true
    versionRange="${sbl_version_range}"
    ordering="BEFORE"
    side="BOTH"